<html>
    <script>
        try{
            const array = new Array(99999999999999999999999)
        }catch(exception){
            console.log(exception)
            console.log()
            console.log(`예외 명 : ${exception.name}`)
            console.log(`예외 메세지 : ${exception.message}`)
        }
    </script>
</html>